name       : mpdris2
version    : '0.7'
release    : 3
homepage   : https://github.com/eonpatapon/mpDris2
source     :
    - https://github.com/eonpatapon/mpDris2/archive/0.7.tar.gz : 41fc24128e13d4d2b58095c8496357079544fb6a52caca234690a6c265e6ba24
license    : GPL-3.0
component  : multimedia.audio
summary    : MPRIS V2.1 support for mpd
description: |
    mpDris2 provide MPRIS 2 support to mpd (Music Player Daemon). mpDris2 is run in the user session and monitors a local or distant mpd server.
setup      : |
    %autogen
rundeps    :
    - mutagen
    - python-dbus
    - python-mpd
build      : |
    %make
install    : |
    %make_install
